name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2, 3.3, jruby-9.1, jruby-9.2, jruby-9.3, jruby-9.4]
        env: [RACK2, RACK3]
        exclude:
          # Rack 3 requires Ruby >= 2.4
          - ruby: 2.3
            env: RACK3
          - ruby: jruby-9.1
            env: RACK3

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "${{ matrix.env }}=1" >> $GITHUB_ENV

      - name: Install gems
        run: |
          bundle config set --local without 'docs'
          bundle install

      - name: Tests
        run: bundle exec rake spec