name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  ruby_version: 3.3

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0', 3.1, 3.2, 3.3, jruby-9.2, jruby-9.3, jruby-9.4]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gems
        run: |
          bundle config set --local with 'test'
          bundle install

      - name: Unit tests
        run: bundle exec rake

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}

      - name: Install gems
        run: |
          bundle config set --local with 'development'
          bundle install

      - name: Rubocop
        run: bundle exec rake rubocop
